services:
  - type: web
    name: my-python-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python3 bot.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        value: YOUR_TELEGRAM_BOT_TOKEN
