services:
  - type: web
    name: my-python-bot
    env: python
    buildCommand: |
      apt-get update && apt-get install -y python3 python3-pip
      pip3 install -r requirements.txt
    startCommand: python3 bot.py
